# Generated by Django 5.2.7 on 2025-10-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
