# Generated by Django 5.2.7 on 2025-10-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='complete_kyc_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deposit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='psw',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
