# Generated by Django 5.2.7 on 2025-10-27 23:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_balance_user_ban_user_complete_kyc_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_to', models.CharField(choices=[('trading', 'trading'), ('holding', 'holding')], default='trading', max_length=100)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('expired', 'expired')], default='pending', max_length=10)),
                ('image', models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='prove')),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
