# Generated by Django 5.2.7 on 2025-10-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_currency_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
