# Generated by Django 5.2.7 on 2025-10-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_deposit_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='minimum_deposit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currency',
            name='transaction_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
