# Generated by Django 5.2.7 on 2025-10-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_currency_minimum_deposit_currency_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
