# Generated by Django 5.2.7 on 2025-11-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_currency_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up_level',
            field=models.IntegerField(default=0),
        ),
    ]
