# Generated by Django 5.2.7 on 2025-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_verified_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency_preference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_tolerance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
