# Generated by Django 5.2.7 on 2025-11-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_currency_preference_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
