# Generated by Django 5.2.7 on 2025-11-03 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_currency_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('min_amount', models.FloatField(default=0.0)),
                ('transaction_fee', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
