# Generated by Django 5.2.7 on 2025-11-03 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_paymentgateway_currency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.paymentgateway'),
        ),
    ]
