# Generated by Django 5.2.7 on 2025-11-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_deposit_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
