# Generated by Django 5.2.7 on 2025-11-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_deposit_grand_total_alter_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
