# Generated by Django 5.2.7 on 2025-11-04 22:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_deposit_transaction_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_from', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=30)),
                ('wallet_address', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('gateway', models.CharField(max_length=50)),
                ('email', models.CharField(verbose_name=30)),
                ('transaction_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
