# Generated by Django 5.2.7 on 2025-11-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='equivalent',
            field=models.FloatField(default=0.0),
        ),
    ]
