# Generated by Django 5.2.7 on 2025-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_plancategory_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='network',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
