# Generated by Django 5.2.7 on 2025-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_withdraw_currency_alter_withdraw_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='equivalent',
            field=models.FloatField(default=0.0),
        ),
    ]
