# Generated by Django 5.2.7 on 2025-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_withdraw_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('expired', 'expired')], default='pending', max_length=10),
        ),
    ]
