# Generated by Django 5.2.7 on 2025-11-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_country_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
