# Generated by Django 5.2.7 on 2025-11-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_address_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_username_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
