# Generated by Django 5.2.7 on 2025-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_user_auto_copy_new_trader_user_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='user',
            name='login_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_whitlist',
            field=models.BooleanField(default=False),
        ),
    ]
