# Generated by Django 5.2.7 on 2025-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_trader_copiedtrader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(default='unverified', max_length=15),
        ),
    ]
