# Generated by Django 5.2.7 on 2025-11-09 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
