# Generated by Django 5.2.7 on 2025-11-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_kycverification_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
    ]
