# Generated by Django 5.2.7 on 2025-11-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_rename_content_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='approveed_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
