# Generated by Django 5.2.7 on 2025-11-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_kycverification_approveed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycverification',
            old_name='approveed_on',
            new_name='approved_on',
        ),
    ]
