# Generated by Django 5.2.7 on 2025-11-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_rename_approveed_on_kycverification_approved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='instructions',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='instructions',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
