# Generated by Django 5.2.7 on 2025-11-10 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_paymentgateway_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('markets', models.TextField()),
                ('volume', models.CharField(max_length=50)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('trading_style', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=100)),
                ('strategy', models.TextField()),
                ('win_rate', models.FloatField()),
                ('trading_statements', models.FileField(upload_to='traders/statements/')),
                ('government_id', models.FileField(upload_to='traders/id/')),
                ('proof_account', models.FileField(upload_to='traders/proof/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
