# Generated by Django 5.2.7 on 2025-11-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_traderapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiedtrader',
            name='created_by',
        ),
    ]
