# Generated by Django 5.2.7 on 2025-11-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_remove_copiedtrader_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balance',
            new_name='holding_deposit',
        ),
        migrations.AddField(
            model_name='user',
            name='holding_profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
    ]
