# Generated by Django 5.2.7 on 2025-11-11 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_rename_balance_user_holding_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='badge',
            field=models.CharField(choices=[('none', 'No Badge'), ('blue', 'Blue Badge'), ('gold', 'Gold Badge')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='copy_mode',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('full', 'Full Balance')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='trader',
            name='require_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trader',
            name='min_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='profit_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
    ]
