# Generated by Django 5.2.7 on 2025-11-12 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_trader_badge_trader_bio_trader_copy_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.FloatField(default=0.0)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('user_balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='account.trader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
