# Generated by Django 5.2.7 on 2025-11-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_copyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('crypto', 'Crypto'), ('stocks', 'Stocks')], max_length=20)),
                ('asset', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('outcome', models.CharField(choices=[('profit', 'Profit'), ('loss', 'Loss')], max_length=10)),
                ('outcome_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_trades', to='account.trader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
