# Generated by Django 5.2.7 on 2025-11-12 23:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='symbol',
            new_name='asset',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pnl_percent',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='size',
        ),
        migrations.AddField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('BUY', 'Buy/Long'), ('SELL', 'Sell/Short')], default='ddd', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='leverage',
            field=models.PositiveIntegerField(default=1, help_text='1 for spot, >1 for leverage'),
        ),
        migrations.AddField(
            model_name='trade',
            name='liquidation_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=23.32, help_text='Amount used for trade', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='position_size',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LIQUIDATED', 'Liquidated')], default='OPEN', max_length=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('LEVERAGE', 'Leverage')], default='SPOT', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
    ]
