# Generated by Django 5.2.7 on 2025-11-12 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_rename_symbol_trade_asset_remove_trade_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='created_at',
            new_name='opened_at',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='asset',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='liquidation_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='position_size',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='trade',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.FloatField(default=23.3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='mode',
            field=models.CharField(choices=[('spot', 'Spot'), ('leverage', 'Leverage')], default='spot', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='pnl_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='leverage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
