# Generated by Django 5.2.7 on 2025-11-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_rename_created_at_trade_opened_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='active',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='leverage',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='opened_at',
        ),
        migrations.AddField(
            model_name='trade',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='size',
            field=models.CharField(default='fd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='ad', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='mode',
            field=models.CharField(default='spot', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10),
        ),
    ]
