# Generated by Django 5.2.7 on 2025-11-12 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_remove_trade_active_remove_trade_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='exit_price',
        ),
        migrations.AddField(
            model_name='trade',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='leverage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='mode',
            field=models.CharField(choices=[('spot', 'Spot'), ('leverage', 'Leverage')], default='spot', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
    ]
