# Generated by Django 5.2.7 on 2025-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_remove_trade_exit_price_trade_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
