# Generated by Django 5.2.7 on 2025-11-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_alter_user_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
