# Generated by Django 5.2.7 on 2025-11-15 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfie',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AddressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('id_type', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='address')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(auto_now=True, null=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
