# Generated by Django 5.2.7 on 2025-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_kycverification_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_trading_volume',
            field=models.FloatField(default=0.0),
        ),
    ]
