# Generated by Django 5.2.7 on 2025-11-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_userpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='from_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.plan'),
        ),
    ]
