# Generated by Django 5.2.7 on 2025-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_deposit_from_plan_userplan_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_global_settings',
            field=models.BooleanField(default=True),
        ),
    ]
