# Generated by Django 5.2.7 on 2025-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiedtrader',
            name='allocation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='copiedtrader',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='copiedtrader',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='copiedtrader',
            name='user_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
