# Generated by Django 5.2.7 on 2025-11-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_copiedtrader_allocation_copiedtrader_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiedtrader',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='copiedtrader',
            name='leverage',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
