# Generated by Django 5.2.7 on 2025-11-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_copiedtrader_amount_copiedtrader_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='asset',
            field=models.CharField(default='crypto', max_length=10),
        ),
    ]
