# Generated by Django 5.2.7 on 2025-11-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_trade_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_on',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ref',
        ),
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('danger', 'Danger'), ('primary', 'Primary'), ('warning', 'Warning')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('icon', 'Icon')], default='text', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
