# Generated by Django 5.2.7 on 2025-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_user_current_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
