# Generated by Django 5.2.7 on 2025-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_alter_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
