# Generated by Django 5.2.7 on 2025-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_deposit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='approved_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
