# Generated by Django 5.2.7 on 2025-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_deposit_approved_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
