# Generated by Django 5.2.7 on 2025-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_deposit_approved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
