# Generated by Django 5.2.7 on 2025-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_deposit_transaction_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('payments', 'Payments'), ('group', 'Group'), ('analytics', 'Analytics'), ('verified', 'Verified')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trader Benefit',
                'verbose_name_plural': 'Trader Benefits',
                'ordering': ['id'],
            },
        ),
    ]
