# Generated by Django 5.2.7 on 2025-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_traderbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
