# Generated by Django 5.2.7 on 2025-11-21 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_trader_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('admin', 'Admin'), ('system', 'System'), ('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='admin', max_length=20)),
                ('icon', models.CharField(default='campaign', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ManualTrade',
        ),
    ]
