# Generated by Django 5.2.7 on 2025-12-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_adminnotification_delete_manualtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trading_circle',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trading_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_authentication_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
