# Generated by Django 5.2.7 on 2025-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_user_trading_circle_user_trading_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmethod',
            name='method_type',
            field=models.CharField(blank=True, choices=[('gateway', 'gateway'), ('currency', 'currency')], max_length=30, null=True),
        ),
    ]
