# Generated by Django 5.2.7 on 2025-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_userpaymentmethod_method_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
