# Generated by Django 5.2.7 on 2025-12-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_user_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_email_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_email_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
