# Generated by Django 5.2.7 on 2025-12-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_emailtemplate_body_content_emailtemplate_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_withdrawal', models.FloatField(blank=True, null=True)),
                ('maximum_withdrawal', models.FloatField(blank=True, null=True)),
                ('platform_name', models.CharField(max_length=100)),
                ('registration_status', models.BooleanField(default=True)),
                ('default_language', models.CharField(default='en', max_length=20)),
                ('default_currency', models.CharField(default='usd', max_length=10)),
                ('email_notification_enabled', models.BooleanField(default=True)),
                ('mandatory_2fa', models.BooleanField(default=False)),
                ('require_security_question', models.BooleanField(default=True)),
                ('minimum_password_length', models.PositiveSmallIntegerField(default=8)),
                ('require_uppercase_password', models.BooleanField(default=True)),
                ('require_lowercase_password', models.BooleanField(default=True)),
                ('require_number_password', models.BooleanField(default=True)),
                ('require_special_character_password', models.BooleanField(default=True)),
                ('failed_loging_attempts_before_lockout', models.PositiveSmallIntegerField(default=5)),
                ('require_login_notification', models.BooleanField(default=False)),
                ('enable_trader_application', models.BooleanField(default=True)),
                ('minimum_trading_balance_trader_application', models.FloatField(default=0)),
                ('minimum_account_age_trader_application', models.PositiveSmallIntegerField(default=20)),
                ('minimum_trading_volume_last_30_days_usd', models.FloatField(default=0)),
                ('application_review_period_days', models.PositiveSmallIntegerField(default=5)),
                ('require_2fa_for_withdrawal', models.BooleanField(default=False)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.BooleanField(default=30)),
                ('kyc_verification', models.BooleanField(default=True)),
                ('required_level_for_kyc', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_limit_for_unverified_user_minimum', models.PositiveSmallIntegerField(default=0)),
                ('transaction_limit_for_unverified_user_maximum', models.PositiveSmallIntegerField(default=0)),
                ('email_verification_enable', models.BooleanField(default=True)),
                ('maximum_verification_email_resend_attempts', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
