# Generated by Django 5.2.7 on 2025-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_config_user_ban_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='min_win_rate',
            field=models.PositiveIntegerField(default=55),
        ),
    ]
