# Generated by Django 5.2.7 on 2025-12-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_config_min_win_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=7200),
        ),
    ]
