# Generated by Django 5.2.7 on 2025-12-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_alter_config_session_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trading_circle_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
