# Generated by Django 5.2.7 on 2025-12-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_user_trading_circle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trading_circle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
