# Generated by Django 5.2.7 on 2025-12-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_alter_user_trading_circle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setup_key_2fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
