from django.urls import path

from account import views

urlpatterns = [
    path('', views.home, name='home'),
    path("stop-copying/<uuid:pk>/", views.stop_copying, name="stop_copying"),
    path('crypto-market/', views.crypto_market, name='crypto_market'),
    path('stock-market/', views.stock_market, name='stock_market'),
    path('place-trade/', views.place_trade, name='place_trade'),
    path('copy-trader/', views.copy_trader, name='copy_trader'),
    path('become-trader/', views.become_trader, name='become_trader'),
    path('deposit/', views.deposit, name='deposit'),
    path('deposit-crypto-details/<uuid:ref>/', views.deposit_crypto_details, name='deposit_details'),
    path('deposit-crypto-pending/<uuid:ref>/', views.deposit_crypto_pending, name='deposit_crypto_pending'),
    path('deposit-crypto-success/<uuid:ref>/', views.deposit_crypto_success, name='deposit_crypto_success'),
    path('deposit-gateway-details/<uuid:ref>/', views.deposit_gateway_details, name='deposit_gateway_details'),
    path('deposit-gateway-pending/<uuid:ref>/', views.deposit_gateway_pending, name='deposit_gateway_pending'),
    path('deposit-gateway-success/<uuid:ref>/', views.deposit_gateway_success, name='deposit_gateway_success'),
    path('deposit-history/', views.deposit_history, name='deposit_history'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('withdrawal-history/', views.withdrawal_history, name='withdrawal_history'),
    path('planning/', views.planning, name='planning'),
    path('referrals/', views.referrals, name='referrals'),
    path('profile/', views.profile, name='profile'),
    path('kyc-verification/', views.kyc_verification, name='kyc_verification'),
    path('address-verification/', views.address_verification, name='address_verification'),
    path('settings/', views.settings, name='settings'),
    path('sign-in/', views.sign_in, name='sign_in'),
    path('logout/', views.logout_view, name='logout'),
    # path('forget-password/', views.forget_password, name='forget_password'),
    path('sign-up-step-1/', views.sign_up_step_1, name='sign_up_step_1'),
    path('sign-up-step-2/', views.sign_up_step_2, name='sign_up_step_2'),
    path('sign-up-step-3/', views.sign_up_step_3, name='sign_up_step_3'),
    path('agreement/', views.copytrading_agreement, name='copytrading_agreement'),
    path('password/change/', views.change_password, name='change_password'),
    path('two-factor/', views.two_factor, name='two_factor'),
]